name: 项目构建（Notes，Ports，Dynmap）

on:
  workflow_dispatch:

jobs:
  BuildNotes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'


      - name: Change Permission
        run:
          sudo chmod -R 777 /home/runner


      - name: Build Nodes
        run: |
          cd nodes
          ./gradlew build


      - name: Upload Releases
        uses: softprops/action-gh-release@v1
        with:
          文件:  ./nodes/build/libs/nodes-*.jar
          draft: true
          fail_on_unmatched_files: true
          
  BuildDynmap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt, clippy


      - name: npm install
        run: |
          cd dynmap
          npm install


      - name: Handle wasm
        run: |
          cd dynmap
          rustup target add wasm32-unknown-unknown
          cargo install -f --version 0.2.100 wasm-bindgen-cli
          npm run wasm


      - name: Build Dynmap
        run: |
          cd dynmap
          npm run build


      - name: Zip Dynmap
        run: |
          zip -r Dynmap.zip ./dynmap/build


      - name: Upload Releases
        uses: softprops/action-gh-release@v1
        with:
          文件:  ./Dynmap.zip
          draft: true
          fail_on_unmatched_files: true


  BuildPorts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'


      - name: Change Permission
        run: |
          sudo chmod -R 777 /home/runner

        
      - name: build ports
        run: |
          cd ports
          ./gradlew build


      - name: Upload Releases
        uses: softprops/action-gh-release@v1
        with:
          文件:  ./ports/build/libs/nodes-ports-*.jar
          draft: true
          fail_on_unmatched_files: true
